apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "35"
  creationTimestamp: "2020-04-03T18:12:07Z"
  generation: 35
  labels:
    app: country
    policy: network
  name: country
  namespace: default
  resourceVersion: "1945458"
  selfLink: /apis/apps/v1/namespaces/default/deployments/country
  uid: a13795d7-75d6-11ea-b345-42010a8400ad
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: country
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: country
    spec:
      containers:
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: POSTGRES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: dbname
              name: cloudsql-db-credentials
        image: alexsn98/country_cn:latest
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "300"
        name: country
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=cloudcomputingproject-272814:europe-west1:data-base=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-07T13:55:39Z"
    lastUpdateTime: "2020-04-07T13:55:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-07T00:23:06Z"
    lastUpdateTime: "2020-04-07T19:16:03Z"
    message: ReplicaSet "country-6d7f5887c7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 35
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
